import {
  Code,
  Heart,
  Music,
  Film,
  Wrench,
  ChefHat,
  Brain,
  Scale,
  GraduationCap,
} from "lucide-react-native";
import { COLORS } from "@/constants/colors";

export const learningCategories = [
  {
    id: "programming",
    title: "Programming & Development",
    description: "Master coding languages and software development",
    icon: Code,
    gradient: [COLORS.DARK_PURPLE, COLORS.BABY_BLUE] as const,
    lessonCount: 15,
    duration: "30 hours",
  },
  {
    id: "health",
    title: "Health & Medicine",
    description: "Understanding health, wellness, and medical basics",
    icon: Heart,
    gradient: [COLORS.BABY_PINK, COLORS.BABY_PINK_DARK] as const,
    lessonCount: 12,
    duration: "24 hours",
  },
  {
    id: "music",
    title: "Music Production",
    description: "Learn music theory, production, and mixing",
    icon: Music,
    gradient: [COLORS.BABY_BLUE, COLORS.BABY_BLUE_DARK] as const,
    lessonCount: 18,
    duration: "36 hours",
  },
  {
    id: "filmmaking",
    title: "Film & Video Production",
    description: "Cinematography, editing, and storytelling",
    icon: Film,
    gradient: [COLORS.DARK_PURPLE_DARK, COLORS.BABY_BLUE] as const,
    lessonCount: 14,
    duration: "28 hours",
  },
  {
    id: "automotive",
    title: "Automotive Mechanics",
    description: "Car maintenance, repair, and diagnostics",
    icon: Wrench,
    gradient: [COLORS.BABY_PINK, COLORS.BABY_BLUE_DARK] as const,
    lessonCount: 10,
    duration: "20 hours",
  },
  {
    id: "culinary",
    title: "Culinary Arts",
    description: "Cooking techniques, recipes, and food science",
    icon: ChefHat,
    gradient: [COLORS.BABY_BLUE_DARK, COLORS.DARK_PURPLE_DARK] as const,
    lessonCount: 16,
    duration: "32 hours",
  },
  {
    id: "psychology",
    title: "Psychology & Wellness",
    description: "Mental health, mindfulness, and well-being",
    icon: Brain,
    gradient: [COLORS.BABY_BLUE, COLORS.BABY_PINK] as const,
    lessonCount: 11,
    duration: "22 hours",
  },
  {
    id: "law",
    title: "Legal Studies",
    description: "Understanding law, rights, and legal systems",
    icon: Scale,
    gradient: [COLORS.BABY_BLUE_DARK, COLORS.BABY_PINK_DARK] as const,
    lessonCount: 13,
    duration: "26 hours",
  },
  {
    id: "academics",
    title: "Academic Excellence",
    description: "Study techniques and subject mastery",
    icon: GraduationCap,
    gradient: [COLORS.BABY_BLUE, COLORS.DARK_PURPLE_LIGHT] as const,
    lessonCount: 20,
    duration: "40 hours",
  },
];

interface Lesson {
  id: string;
  title: string;
  description: string;
  duration: string;
  difficulty?: "Beginner" | "Intermediate" | "Advanced";
}

export const lessons: Record<string, Lesson[]> = {
  programming: [
    {
      id: "prog-1",
      title: "Introduction to Programming",
      description: "Learn the fundamentals of programming and computational thinking",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "prog-2",
      title: "Variables and Data Types",
      description: "Understanding different data types and how to use variables",
      duration: "1.5 hours",
      difficulty: "Beginner",
    },
    {
      id: "prog-3",
      title: "Control Flow and Logic",
      description: "Master if statements, loops, and logical operators",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "prog-4",
      title: "Functions and Modules",
      description: "Creating reusable code with functions and organizing with modules",
      duration: "2.5 hours",
      difficulty: "Intermediate",
    },
    {
      id: "prog-5",
      title: "Object-Oriented Programming",
      description: "Classes, objects, inheritance, and polymorphism",
      duration: "3 hours",
      difficulty: "Intermediate",
    },
  ],
  health: [
    {
      id: "health-1",
      title: "Nutrition Basics",
      description: "Understanding macronutrients, vitamins, and balanced diet",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "health-2",
      title: "Exercise and Fitness",
      description: "Types of exercise, creating workout routines, and staying active",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "health-3",
      title: "Mental Health Awareness",
      description: "Recognizing signs, coping strategies, and seeking help",
      duration: "1.5 hours",
      difficulty: "Beginner",
    },
    {
      id: "health-4",
      title: "Sleep Science",
      description: "Understanding sleep cycles and improving sleep quality",
      duration: "1.5 hours",
      difficulty: "Intermediate",
    },
  ],
  music: [
    {
      id: "music-1",
      title: "Music Theory Fundamentals",
      description: "Notes, scales, chords, and basic harmony",
      duration: "2.5 hours",
      difficulty: "Beginner",
    },
    {
      id: "music-2",
      title: "Digital Audio Workstations",
      description: "Introduction to DAWs and basic recording techniques",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "music-3",
      title: "Mixing and Mastering",
      description: "EQ, compression, effects, and finalizing tracks",
      duration: "3 hours",
      difficulty: "Intermediate",
    },
    {
      id: "music-4",
      title: "Sound Design",
      description: "Creating unique sounds and textures",
      duration: "2.5 hours",
      difficulty: "Advanced",
    },
  ],
  filmmaking: [
    {
      id: "film-1",
      title: "Storytelling Basics",
      description: "Three-act structure, character development, and plot",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "film-2",
      title: "Camera Techniques",
      description: "Shots, angles, movement, and composition",
      duration: "2.5 hours",
      difficulty: "Beginner",
    },
    {
      id: "film-3",
      title: "Lighting for Film",
      description: "Three-point lighting, mood, and atmosphere",
      duration: "2 hours",
      difficulty: "Intermediate",
    },
    {
      id: "film-4",
      title: "Video Editing",
      description: "Cutting, transitions, and post-production workflow",
      duration: "3 hours",
      difficulty: "Intermediate",
    },
  ],
  automotive: [
    {
      id: "auto-1",
      title: "Car Basics",
      description: "Understanding major components and systems",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "auto-2",
      title: "Regular Maintenance",
      description: "Oil changes, filters, fluids, and preventive care",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "auto-3",
      title: "Troubleshooting Common Issues",
      description: "Diagnosing problems and understanding warning signs",
      duration: "2.5 hours",
      difficulty: "Intermediate",
    },
  ],
  culinary: [
    {
      id: "culinary-1",
      title: "Knife Skills",
      description: "Proper techniques, safety, and essential cuts",
      duration: "1.5 hours",
      difficulty: "Beginner",
    },
    {
      id: "culinary-2",
      title: "Cooking Methods",
      description: "Sautéing, roasting, braising, and more",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "culinary-3",
      title: "Flavor Development",
      description: "Building layers of flavor and balancing tastes",
      duration: "2 hours",
      difficulty: "Intermediate",
    },
    {
      id: "culinary-4",
      title: "Plating and Presentation",
      description: "Making dishes visually appealing",
      duration: "1.5 hours",
      difficulty: "Intermediate",
    },
  ],
  psychology: [
    {
      id: "psych-1",
      title: "Understanding Emotions",
      description: "Emotional intelligence and regulation",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "psych-2",
      title: "Stress Management",
      description: "Techniques for reducing and coping with stress",
      duration: "1.5 hours",
      difficulty: "Beginner",
    },
    {
      id: "psych-3",
      title: "Mindfulness and Meditation",
      description: "Practices for present-moment awareness",
      duration: "2 hours",
      difficulty: "Beginner",
    },
  ],
  law: [
    {
      id: "law-1",
      title: "Legal System Overview",
      description: "Understanding courts, laws, and legal processes",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "law-2",
      title: "Your Rights",
      description: "Constitutional rights and civil liberties",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "law-3",
      title: "Contracts and Agreements",
      description: "Understanding legal documents and obligations",
      duration: "2.5 hours",
      difficulty: "Intermediate",
    },
  ],
  academics: [
    {
      id: "academic-1",
      title: "Effective Study Techniques",
      description: "Active recall, spaced repetition, and note-taking",
      duration: "2 hours",
      difficulty: "Beginner",
    },
    {
      id: "academic-2",
      title: "Time Management",
      description: "Planning, prioritizing, and productivity",
      duration: "1.5 hours",
      difficulty: "Beginner",
    },
    {
      id: "academic-3",
      title: "Research Skills",
      description: "Finding, evaluating, and citing sources",
      duration: "2 hours",
      difficulty: "Intermediate",
    },
    {
      id: "academic-4",
      title: "Writing Excellence",
      description: "Essay structure, argumentation, and style",
      duration: "2.5 hours",
      difficulty: "Intermediate",
    },
  ],
};