import {
  MessageCircle,
  Languages,
  PenTool,
  BarChart3,
  Calendar,
  Search,
  TrendingUp,
  Headphones,
  Palette,
  Code2,
  FolderKanban,
  DollarSign,
  MapPin,
  Dumbbell,
  Flower2,
  Code,
  Heart,
  Music,
  Film,
  Wrench,
  ChefHat,
  Brain,
  Scale,
  GraduationCap,
  Image,
} from "lucide-react-native";

export const specialists = [
  {
    id: "general",
    name: "General AI Assistant",
    description: "Your all-purpose AI companion for any task",
    icon: MessageCircle,
    gradient: ["#667eea", "#764ba2"] as const,
    chatGradient: ["#667eea", "#764ba2", "#f093fb"] as const,
    welcomeMessage: "Hello! I'm your General AI Assistant powered by ChatGPT-4o, available for free to help with any questions or tasks you have. I can assist with general information, basic problem-solving, casual conversations, and much more. Whether you need quick answers, brainstorming help, or just want to chat, I'm here for you! What can I help you with today?",
    isFree: true,
  },
  {
    id: "language-translator",
    name: "Language Translator",
    description: "Professional translation & language learning",
    icon: Languages,
    gradient: ["#4facfe", "#00f2fe"] as const,
    chatGradient: ["#4facfe", "#00f2fe", "#43e97b"] as const,
    welcomeMessage: "¡Hola! Bonjour! 你好! I'm your Language Translator specialist powered by ChatGPT-4o. I can translate text between 100+ languages, help you learn new languages, explain grammar rules, provide pronunciation guides, and assist with cultural context. Whether you're traveling, studying, or conducting international business, I'm here to break down language barriers!",
    isFree: true,
  },
  {
    id: "content-creator",
    name: "Content Creator",
    description: "Social media, blogs, marketing content",
    icon: PenTool,
    gradient: ["#fa709a", "#fee140"] as const,
    chatGradient: ["#fa709a", "#fee140", "#667eea"] as const,
    welcomeMessage: "Hey there, content creator! 🎨 I'm your Content Creation specialist. I can help you craft engaging social media posts, write compelling blog articles, create marketing copy, develop content strategies, brainstorm viral ideas, and optimize your content for different platforms. Let's create something amazing together!",
    isFree: true,
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    description: "Data insights, analysis & visualization",
    icon: BarChart3,
    gradient: ["#667eea", "#764ba2"] as const,
    chatGradient: ["#667eea", "#764ba2", "#f093fb"] as const,
    welcomeMessage: "Hello! I'm your Data Analyst specialist. I can help you interpret data, create visualizations, perform statistical analysis, identify trends and patterns, build predictive models, and turn raw data into actionable insights. Share your data challenges and let's uncover the story your data is telling!",
    tier: "premium",
  },
  {
    id: "virtual-assistant",
    name: "Virtual Assistant",
    description: "Task management, scheduling & organization",
    icon: Calendar,
    gradient: ["#a8edea", "#fed6e3"] as const,
    chatGradient: ["#a8edea", "#fed6e3", "#667eea"] as const,
    welcomeMessage: "Good day! I'm your Virtual Assistant, ready to help you stay organized and productive. I can assist with scheduling, task management, email drafting, meeting preparation, travel planning, and general administrative tasks. Think of me as your personal productivity partner!",
    tier: "premium",
  },
  {
    id: "research-assistant",
    name: "Research Assistant",
    description: "Academic research, fact-checking & analysis",
    icon: Search,
    gradient: ["#ffecd2", "#fcb69f"] as const,
    chatGradient: ["#ffecd2", "#fcb69f", "#4facfe"] as const,
    welcomeMessage: "Greetings, researcher! 📚 I'm your Research Assistant specialist. I can help you conduct thorough research, fact-check information, analyze sources, create bibliographies, summarize academic papers, and assist with research methodology. Let's dive deep into knowledge together!",
    isFree: true,
  },
  {
    id: "marketing-expert",
    name: "Marketing Expert",
    description: "Digital marketing, SEO & growth strategies",
    icon: TrendingUp,
    gradient: ["#ff9a9e", "#fecfef"] as const,
    chatGradient: ["#ff9a9e", "#fecfef", "#ffecd2"] as const,
    welcomeMessage: "Hey there, marketer! 🚀 I'm your Marketing Expert specialist. I can help you develop marketing strategies, optimize SEO, create ad campaigns, analyze market trends, build brand identity, and grow your audience. Let's boost your marketing game and drive real results!",
    tier: "premium",
  },
  {
    id: "customer-support",
    name: "Customer Support Agent",
    description: "Customer service & support strategies",
    icon: Headphones,
    gradient: ["#a18cd1", "#fbc2eb"] as const,
    chatGradient: ["#a18cd1", "#fbc2eb", "#667eea"] as const,
    welcomeMessage: "Hello! I'm your Customer Support specialist. I can help you handle customer inquiries, develop support strategies, create FAQ content, improve customer satisfaction, resolve complaints, and build better customer relationships. How can I help you serve your customers better?",
    tier: "premium",
  },
  {
    id: "creative-assistant",
    name: "Creative Assistant",
    description: "Art, design & creative project guidance",
    icon: Palette,
    gradient: ["#667eea", "#764ba2"] as const,
    chatGradient: ["#667eea", "#764ba2", "#f093fb"] as const,
    welcomeMessage: "Welcome, creative soul! 🎨 I'm your Creative Assistant specialist. I can help you brainstorm creative ideas, provide design feedback, suggest color palettes, guide artistic projects, develop creative concepts, and overcome creative blocks. Let's unleash your creativity together!",
    tier: "premium",
  },
  {
    id: "technical-expert",
    name: "Technical Expert",
    description: "Advanced tech support & system architecture",
    icon: Code2,
    gradient: ["#4facfe", "#00f2fe"] as const,
    chatGradient: ["#4facfe", "#00f2fe", "#43e97b"] as const,
    welcomeMessage: "Hello, tech enthusiast! 💻 I'm your Technical Expert specialist. I can help with system architecture, troubleshooting complex technical issues, code reviews, technology recommendations, infrastructure planning, and advanced technical problem-solving. What technical challenge can I help you tackle?",
    tier: "premium",
  },
  {
    id: "project-manager",
    name: "Project Manager",
    description: "Project planning, team coordination & delivery",
    icon: FolderKanban,
    gradient: ["#fa709a", "#fee140"] as const,
    chatGradient: ["#fa709a", "#fee140", "#667eea"] as const,
    welcomeMessage: "Hello, project leader! 📋 I'm your Project Manager specialist. I can help you plan projects, manage timelines, coordinate teams, track progress, handle risks, and ensure successful project delivery. Let's get your projects organized and on track!",
    tier: "premium",
  },
  {
    id: "financial-advisor",
    name: "Financial Advisor",
    description: "Personal finance, investments & budgeting",
    icon: DollarSign,
    gradient: ["#43e97b", "#38f9d7"] as const,
    chatGradient: ["#43e97b", "#38f9d7", "#667eea"] as const,
    welcomeMessage: "Welcome! I'm your Financial Advisor specialist. I can help you with budgeting, investment strategies, financial planning, debt management, savings goals, and understanding financial markets. Please note: I provide educational information only - consult a licensed financial advisor for personalized advice. How can I help with your financial goals?",
    tier: "premium",
  },
  {
    id: "travel-planner",
    name: "Travel Planner",
    description: "Trip planning, destinations & travel tips",
    icon: MapPin,
    gradient: ["#667eea", "#764ba2"] as const,
    chatGradient: ["#667eea", "#764ba2", "#f093fb"] as const,
    welcomeMessage: "Bon voyage! ✈️ I'm your Travel Planner specialist. I can help you plan amazing trips, suggest destinations, find the best deals, create itineraries, provide travel tips, recommend accommodations, and help you navigate travel requirements. Where would you like to explore next?",
    tier: "premium",
  },
  {
    id: "fitness-coach",
    name: "Fitness Coach",
    description: "Workout plans, nutrition & wellness guidance",
    icon: Dumbbell,
    gradient: ["#ff9a9e", "#fecfef"] as const,
    chatGradient: ["#ff9a9e", "#fecfef", "#ffecd2"] as const,
    welcomeMessage: "Hey there, fitness enthusiast! 💪 I'm your Fitness Coach specialist. I can help you create workout plans, provide nutrition guidance, set fitness goals, track progress, suggest exercises, and motivate you on your wellness journey. Remember: consult healthcare professionals for medical advice. Ready to get fit?",
    tier: "premium",
  },
  {
    id: "gardening",
    name: "Gardening Expert",
    description: "Plant care, garden planning & growing tips",
    icon: Flower2,
    gradient: ["#43e97b", "#38f9d7"] as const,
    chatGradient: ["#43e97b", "#38f9d7", "#667eea"] as const,
    welcomeMessage: "Welcome to your personal gardening assistant! 🌱 I'm here to help you grow beautiful plants and maintain a thriving garden. I can provide personalized advice based on your location, climate, soil type, and specific gardening goals. Whether you're a beginner or experienced gardener, I can help with plant identification, care schedules, pest management, seasonal planning, and much more. What gardening challenge can I help you with today?",
    tier: "premium",
  },
  {
    id: "coding",
    name: "Coding Expert",
    description: "Debug, optimize, and learn programming",
    icon: Code,
    gradient: ["#667eea", "#764ba2"] as const,
    chatGradient: ["#667eea", "#764ba2", "#f093fb"] as const,
    welcomeMessage: "Hello! I'm your coding expert powered by ChatGPT-4o. I can help you debug code, suggest optimizations, explain programming concepts, and review your code for best practices. Share your code or ask me anything about programming!",
    isFree: true,
  },
  {
    id: "medical",
    name: "Medical Advisor",
    description: "Health guidance and medical information",
    icon: Heart,
    gradient: ["#f093fb", "#f5576c"] as const,
    chatGradient: ["#f093fb", "#f5576c", "#4facfe"] as const,
    welcomeMessage: "Welcome! I'm your medical advisor. I can provide general health information, explain medical conditions, and offer wellness tips. Remember, I'm here for educational purposes only - always consult a healthcare professional for personal medical advice.",
    tier: "premium",
  },
  {
    id: "music",
    name: "Music Producer",
    description: "Music creation and production tips",
    icon: Music,
    gradient: ["#667eea", "#764ba2"] as const,
    chatGradient: ["#667eea", "#764ba2", "#f093fb"] as const,
    welcomeMessage: "Hey there! I'm your music production specialist. I can help with mixing techniques, composition advice, gear recommendations, and music theory. What aspect of music production would you like to explore?",
    tier: "premium",
  },
  {
    id: "film",
    name: "Film Director",
    description: "Filmmaking and storytelling guidance",
    icon: Film,
    gradient: ["#fa709a", "#fee140"] as const,
    chatGradient: ["#fa709a", "#fee140", "#667eea"] as const,
    welcomeMessage: "Greetings! I'm your film directing consultant. I can assist with cinematography, storytelling techniques, editing advice, and production planning. What's your vision, and how can I help bring it to life?",
    tier: "premium",
  },
  {
    id: "mechanic",
    name: "Auto Mechanic",
    description: "Vehicle maintenance and repair help",
    icon: Wrench,
    gradient: ["#a8edea", "#fed6e3"] as const,
    chatGradient: ["#a8edea", "#fed6e3", "#667eea"] as const,
    welcomeMessage: "Hi! I'm your auto mechanic advisor. I can help diagnose car problems, explain maintenance procedures, and provide repair guidance. What issues are you experiencing with your vehicle?",
    tier: "premium",
  },
  {
    id: "chef",
    name: "Culinary Chef",
    description: "Cooking techniques and recipes",
    icon: ChefHat,
    gradient: ["#ffecd2", "#fcb69f"] as const,
    chatGradient: ["#ffecd2", "#fcb69f", "#4facfe"] as const,
    welcomeMessage: "Bonjour! I'm your culinary expert. I can share recipes, cooking techniques, ingredient substitutions, and plating tips. What delicious creation would you like to explore today?",
    tier: "premium",
  },
  {
    id: "therapist",
    name: "Therapist",
    description: "Mental wellness and coping strategies",
    icon: Brain,
    gradient: ["#a18cd1", "#fbc2eb"] as const,
    chatGradient: ["#a18cd1", "#fbc2eb", "#667eea"] as const,
    welcomeMessage: "Hello, I'm here to support your mental wellness journey. I can offer coping strategies, stress management techniques, and general emotional support. Remember, while I provide guidance, professional therapy is recommended for serious concerns. How can I help you today?",
    tier: "premium",
  },
  {
    id: "legal",
    name: "Legal Advisor",
    description: "Legal information and guidance",
    icon: Scale,
    gradient: ["#ff9a9e", "#fecfef"] as const,
    chatGradient: ["#ff9a9e", "#fecfef", "#ffecd2"] as const,
    welcomeMessage: "Good day! I'm your legal information specialist. I can explain legal concepts, provide general legal information, and help you understand your rights. Please note that I provide educational information only - consult a licensed attorney for legal advice.",
    tier: "premium",
  },
  {
    id: "tutor",
    name: "Tutor",
    description: "Academic support and learning",
    icon: GraduationCap,
    gradient: ["#ffecd2", "#fcb69f"] as const,
    chatGradient: ["#ffecd2", "#fcb69f", "#4facfe"] as const,
    welcomeMessage: "Welcome! I'm your personal tutor powered by ChatGPT-4o. I can help with homework, explain complex concepts, provide study strategies, and support your learning journey. What subject would you like to explore today?",
    isFree: true,
  },
  {
    id: "image-generator",
    name: "Image Generator",
    description: "Advanced AI image creation and visual content",
    icon: Image,
    gradient: ["#667eea", "#764ba2"] as const,
    chatGradient: ["#667eea", "#764ba2", "#f093fb"] as const,
    welcomeMessage: "Welcome to the future of image creation! 🎨✨ I'm your Advanced Image Generator specialist, powered by cutting-edge AI technology. I can create stunning, high-quality images from your descriptions - from photorealistic portraits and landscapes to abstract art, logos, illustrations, and creative concepts. Whether you need professional marketing visuals, artistic masterpieces, or unique creative content, I'll bring your imagination to life with precision and creativity. Simply describe what you envision, and I'll generate multiple high-quality options for you. What would you like me to create today?",
    tier: "premium",
  },
];